server:
  port: 8080  # Not used in stdio mode, but required by Spring Boot

spring:
  application:
    name: mcp-campaign-server-stdio
  main:
    web-application-type: none
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    com.insurance.mcp: INFO
    org.springframework: WARN
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    enabled-by-default: false

# MCP Server Configuration for Stdio Mode
mcp:
  server:
    name: "Insurance Campaign MCP Server (Stdio)"
    version: "1.0.0"
    protocol-version: "2024-11-05"
    capabilities:
      tools: true
      inspector: true
      resources: false
      prompts: false
      logging: false
      streaming: false  # Stdio doesn't support streaming
      authentication: false
    transport: "stdio"
    stdio:
      enabled: true
    http-stream:
      enabled: false
    streamable-http:
      enabled: false
  websocket:
    enabled: false

# Web server is disabled above in spring.main.web-application-type
