server:
  port: 8081
  servlet:
    context-path: /
  http2:
    enabled: false

spring:
  application:
    name: mcp-campaign-server
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    com.insurance.mcp: INFO
    org.springframework.web.socket: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# MCP Server Configuration
mcp:
  server:
    name: "Insurance Campaign MCP Server"
    version: "1.0.0"
    protocol-version: "2024-11-05"
    capabilities:
      tools: true
      inspector: true
      resources: false
      prompts: false
      logging: false
      streaming: true
      authentication: false
    transport: "streamable-http"
    stdio:
      enabled: true   # Set to true for stdio mode
    http-stream:
      enabled: false  # Legacy HTTP Stream support
    streamable-http:
      enabled: true   # Enable Streamable HTTP Transport (recommended)
  websocket:
    enabled: false  # Disable legacy WebSocket support
    path: "/mcp"
    allowed-origins: "*"
  http-stream:
    path: "/mcp-stream"
    allowed-origins: "*"
  streamable-http:
    path: "/mcp/v1"
    allowed-origins: "*"
    authentication:
      enabled: false
      oauth2:
        enabled: false
      api-key:
        enabled: false
      bearer-token:
        enabled: false
      custom-headers:
        enabled: false